### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [vaibhavirohilla741/Operationalizing-ML#1]
Like this
![image](https://user-images.githubusercontent.com/68433936/104811875-86e2a780-5824-11eb-92d7-0b8259a70219.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by vaibhavirohilla741** [comment]
> I would like to work on this.

Sure 😃

**Comment by samir-0711** [comment]
Can you assign me this issue. And add DWOC and Level label in it.

**Comment by vaibhavirohilla741** [comment]
> Can you assign me this issue. And add DWOC and Level label in it.

Sure what are you going to work on?
I'll label it accordingly.

**Comment by samir-0711** [comment]
I will add code in README.md file which will automatically add contributors in the table.

**Comment by vaibhavirohilla741** [comment]
Here you go!
