### ISSUE TITLE
Beautifying readme

### ISSUE THREAD

**Issue by himanshu007-creator** [vaibhavirohilla741/Operationalizing-ML#13]
## 💥 Proposal
HI, i would like to beautify readme of this repository in following ways:-
- add a banner
- add emojis wherever required
- add other improvements as well

Please add DWOC and level-2 tag to it and assign  me this issue. Thanks.

**Comment by vaibhavirohilla741** [comment]
You can work on the project but I will give only level 1😊

**Comment by himanshu007-creator** [comment]
> You can work on the project but I will give only level 1😊

@vaibhavirohilla741 mam, let's make it fun I will send the pr, if it's just ok make it level one, but if you found it superb make it level 2🤓.
How this sounds?

**Comment by vaibhavirohilla741** [comment]
Sure!!

**Comment by himanshu007-creator** [comment]
https://github.com/vaibhavirohilla741/Operationalizing-ML/pull/14 Its a go :green_circle::small_red_triangle:

**Comment by himanshu007-creator** [comment]
> Sure!!

So was it level 1 or level 2 effort? 🤓
