### ISSUE TITLE
Add Contributers name in the table and last

### ISSUE THREAD

**Issue by Ayush7614** [vaibhavirohilla741/Operationalizing-ML#15]
**Is your feature request related to a problem? Please describe.**

Add Contributers name in the table and last

**Describe the solution you'd like**

![screenshot-github com-2021 02 07-22_11_43](https://user-images.githubusercontent.com/67006255/107153115-d6cf0d00-6991-11eb-8bf5-aa0d555dff2c.png)

**Comment by Ayush7614** [comment]
Like this plss assign me this issue under DWOC and plss level it

**Comment by Ayush7614** [comment]
Add project admin and strangers part also so it looks like good

**Comment by archana-9430** [comment]
Can I work on this under GSSoC'21 @Ayush7614

**Comment by vaibhavirohilla741** [comment]
Yes @Ayush7614.
But I have already added contributors name in the readme.
Try doing something else.

All the best for dwoc and gssoc☺️

**Comment by anirudhsai20** [comment]
Hi @Ayush7614 . Please allow me to work on this issue under GSSOC.

**Comment by starlightknown** [comment]
hey this is done by all contributors bot, you dont have to add it manually
