### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [vaibhavirohilla741/Operationalizing-ML#18]
Hey!
I would like to add the following in the contributing.md -

1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream

**Comment by sahilempire** [comment]
Hello @khareyash05 , I want to work on this issue please assign me.

Thank You.

**Comment by khareyash05** [comment]
@sahilempire I myself am a participant I have opened the issue and want to self work on it
Thank You

**Comment by akashthedeveloper** [comment]
@vaibhavirohilla741 Can you assign to me so that I can work on it.
