### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [vaibhavirohilla741/Operationalizing-ML#2]
Hi @vaibhavirohilla741 

I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by vaibhavirohilla741** [comment]
> Hi @vaibhavirohilla741 
> 
> I would like to contribute to this amazing project
> I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message
> 
> Let me know if you are interested
> 
> Kindly do assign me
> Kindly do add the DWOC and Level label

Hey akrish4 thank you for your suggestions.
I will assign you.
Please make the changes 
😊

**Comment by akrish4** [comment]
thank you @vaibhavirohilla741 
pls add the DWOC and Level label

**Comment by akrish4** [comment]
pls add DWOC and Level label
there are 5 (Level-1 , Level-2 , Level-3 , Level-4 , Level-5) labels
kindly add a label you think would be appropriate

**Comment by akrish4** [comment]
hi @vaibhavirohilla741 
kindly let me know why have you closed the issue

**Comment by akrish4** [comment]
Hi @vaibhavirohilla741 
Now you just have to install and configure the bot using the official github app https://github.com/apps/welcome and rest bot will do since I have added the config.yml file 
Theses bot are made by github only

**Comment by vaibhavirohilla741** [comment]
> Hi @vaibhavirohilla741 
> Now you just have to install and configure the bot using the official github app https://github.com/apps/welcome and rest bot will do since I have added the config.yml file 
> Theses bot are made by github only 

Sure 
Thanks for your time☺️
