### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [vaibhavirohilla741/Operationalizing-ML#26]
I would like to add a code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by vaibhavirohilla741** [comment]
hello @Ayushbajpai19 @muthuannamalai12  the code of conduct file is already added please first go through the project files and then raise a issue.
best of luck for gssoc2021!

**Comment by muthuannamalai12** [comment]
@vaibhavirohilla741 When we click on the code of conduct hyperlink in Custom message shown by welcome bot it say 404 page not found error.

**Comment by muthuannamalai12** [comment]
@vaibhavirohilla741 Can I start working on it??

**Comment by vaibhavirohilla741** [comment]
Yeah!

**Comment by akashthedeveloper** [comment]
@vaibhavirohilla741 Can i work on this issue and contribute to project

**Comment by vaibhavirohilla741** [comment]
Yes @435akashjha don't ask same question.
Do the changes I'll provide you gssoc label😁.
Best of luck!!

**Comment by Avnish5** [comment]
Kindly assign me this issue under GSSOC 2021.
