### ISSUE TITLE
PR Template Not working

### ISSUE THREAD

**Issue by muthuannamalai12** [vaibhavirohilla741/Operationalizing-ML#28]
The PR template is not showing up when we create a PR. I would love to work on this and correct it. Kindly assign me this issue as a part of  Girl Script Summer Of Code.

**Comment by vaibhavirohilla741** [comment]
Ok you can work on it.

**Comment by vaibhavirohilla741** [comment]
@muthuannamalai12 are you working on this or should I close this issue?

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 are you working on this or should I close this issue?

I have created a Pr no: #29 for this issue and it has been merged too

**Comment by vaibhavirohilla741** [comment]
Oh ok.
