### ISSUE TITLE
I want to add no.of forks,stars,pr's,issues and other logos in the readme file .

### ISSUE THREAD

**Issue by srisatya12** [vaibhavirohilla741/Operationalizing-ML#38]
I want to add no.of forks,pr's,stars and other logos in the readme file
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115118890-24d04480-9fc3-11eb-8bd5-ed59901467b5.png)
I want to work on this . Please assign me this issue.

**Comment by srisatya12** [comment]
Thank you @vaibhavirohilla741 . can you please add some tags to this issue.

**Comment by vaibhavirohilla741** [comment]
Sure!! @srisatya1197 
I'll add them in PR don't worry. GSSOC right??

**Comment by srisatya12** [comment]
Yes @vaibhavirohilla741 .
