### ISSUE TITLE
ISSUE TEMPLATE 

### ISSUE THREAD

**Issue by akrish4** [vaibhavirohilla741/Operationalizing-ML#4]
I would like to add issue templates , which will have 3 templates namely bug , feature and proposal templates
It would help the maintainers to understand about what the issue is about
kindly do assign me

**Comment by vaibhavirohilla741** [comment]
Ok you are good to go!

**Comment by akrish4** [comment]
thank you @vaibhavirohilla741 
pls add DWOC and Level label
there are 5 (Level-1 , Level-2 , Level-3 , Level-4 , Level-5) labels
kindly add a label you think would be appropriate

**Comment by akrish4** [comment]
hi @vaibhavirohilla741 
kindly let me know why have you closed the issue

**Comment by vaibhavirohilla741** [comment]
> hi @vaibhavirohilla741 
> kindly let me know why have you closed the issue

Do the changes fast

**Comment by akrish4** [comment]
yes sure

**Comment by akrish4** [comment]
Hi @vaibhavirohilla741 
I have worked on it , kindly do check and merge it 
#6   PR
kindly add the same labels
