### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by tharunc** [vaibhavirohilla741/Operationalizing-ML#5]
Hello there,
     I would like to add CODE_OF_CONDUCT file for this repo as a part of **DWOC**. Kindly assign me this issue.
         THANK YOU

**Comment by vaibhavirohilla741** [comment]
You are good to go☺️

**Comment by vaibhavirohilla741** [comment]
You done?

**Comment by tharunc** [comment]
Kindly ASSIGN me.
