### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [vaibhavirohilla741/Operationalizing-ML#7]
**Is your feature request related to a problem? Please describe.**
----
- I would like to add a contributing.md file which has all aontributing guidelines and git workflow so that everyone can look into it before contributing 

**Describe the solution you'd like**
----
- A markdown file with all contents 

**Describe alternatives you've considered**
----
- No alternative needed , I am experienced 

Kindly assign me

**Comment by vaibhavirohilla741** [comment]
> **Is your feature request related to a problem? Please describe.**
> ----
> - I would like to add a contributing.md file which has all aontributing guidelines and git workflow so that everyone can look into it before contributing 
> 
> **Describe the solution you'd like**
> ----
> - A markdown file with all contents 
> 
> **Describe alternatives you've considered**
> ----
> - No alternative needed , I am experienced 
> 
> Kindly assign me 
> 

You are good to go akrish4

**Comment by akrish4** [comment]
kindly assign

**Comment by vaibhavirohilla741** [comment]
You done?

**Comment by akrish4** [comment]
yeah , I can open a pr soon
