### ISSUE TITLE
welcome bot integration

### ISSUE THREAD

**Issue by Sloth-Panda** [vaibhavirohilla741/Operationalizing-ML#8]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Let me know if this needs to be done

**Comment by vaibhavirohilla741** [comment]
Hey!
I already have someone who is working on the same issue.
Thanks for your time😁

**Comment by Sloth-Panda** [comment]
oh sorry did not see that closing this one
